package moe.kurenai.tdlight.model.chat

enum class ChatAction {
    TYPING, UPLOAD_PHOTO, RECORD_VIDEO, UPLOAD_VIDEO, RECORD_VOICE, UPLOAD_VOICE, UPLOAD_DOCUMENT, FIND_LOCATION, RECORD_VIDEO_NOTE, UPLOAD_VIDEO_NOTE, CHOOSE_STICKER
}